<?php

namespace Database\Factories;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class ProductFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Product::class;

    /**
     * Track the current index.
     *
     * @var int
     */
    protected $index = 0;

    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        $productData = [
            [
                'nama_produk' => 'Jumbo Air Radiator',
                'deskripsi_singkat' => 'Air Radiator',
                'deskripsi' => 'Air Radiator bisa digunakan untuk berbagai motor apa saja yang sudah menggunakan radiator',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0002',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'radiator1' . '.jpg',
            ],
            [
                'nama_produk' => 'Max Care Auto',
                'deskripsi_singkat' => 'Air Radiator',
                'deskripsi' => 'Air Radiator bisa digunakan untuk berbagai motor apa saja yang sudah menggunakan radiator',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0001',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'radiator2' . '.jpg',
            ],
            [
                'nama_produk' => 'Modiesha',
                'deskripsi_singkat' => 'Air Radiator',
                'deskripsi' => 'Air Radiator bisa digunakan untuk berbagai motor apa saja yang sudah menggunakan radiator',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0003',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'radiator3' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Busi Motor',
                'deskripsi_singkat' => 'Busi Motor',
                'deskripsi' => 'Busi Motor bisa digunakan untuk berbagai motor bebek yamaha',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0004',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'busi1' . '.jpg',
            ],
            [
                'nama_produk' => 'Ngk',
                'deskripsi_singkat' => 'Busi Motor',
                'deskripsi' => 'Busi Motor bisa digunakan untuk berbagai motor matic honda',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0005',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'busi2' . '.jpg',
            ],
            [
                'nama_produk' => 'Rtc',
                'deskripsi_singkat' => 'Busi Motor',
                'deskripsi' => 'Busi Motor bisa digunakan untuk berbagai motor bebek honda',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0006',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'busi3' . '.jpg',
            ],
            [
                'nama_produk' => 'Wilwood',
                'deskripsi_singkat' => 'Busi Motor',
                'deskripsi' => 'Busi Motor bisa digunakan untuk berbagai motor bebek',
                'harga_normal' => 18000,
                'SKU' => 'ONDR0007',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 56,
                'image' => 'busi4' . '.jpg',
            ],
            [
                'nama_produk' => 'Rodaparts',
                'deskripsi_singkat' => 'Busi Motor',
                'deskripsi' => 'Busi Motor bisa digunakan untuk berbagai motor bebek',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0008',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'busi5' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamaha Busi',
                'deskripsi_singkat' => 'Busi Motor',
                'deskripsi' => 'Busi Motor bisa digunakan untuk berbagai motor',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0009',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 58,
                'image' => 'busi6' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Busi Motor',
                'deskripsi_singkat' => 'busi motor',
                'deskripsi' => 'busi motor bisa digunakan untuk berbagai motor',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0010',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 56,
                'image' => 'busi7' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamaha Kampas Vega Jupiter',
                'deskripsi_singkat' => 'Kampas Belakang',
                'deskripsi' => 'Kampas rem belakang bisa digunakan untuk motor Fiz-E,Fiz-R,Crypton,Vega,Vega R,Jupiter Z',
                'harga_normal' => 65000,
                'SKU' => 'ONDR0011',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'kampas1' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamaha Kampas Vega ZR',
                'deskripsi_singkat' => 'Kampas Belakang',
                'deskripsi' => 'Kampas rem belakang bisa digunakan untuk motor Vega ZR',
                'harga_normal' => 65000,
                'SKU' => 'ONDR0012',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'kampas2' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Kampas Belakang',
                'deskripsi_singkat' => 'Kampas Belakang',
                'deskripsi' => 'Kampas rem belakang bisa digunakan untuk motor Gl 100,Grand,Legenda,Supra,Supra X,Supra Fit',
                'harga_normal' => 60000,
                'SKU' => 'ONDR0013',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 56,
                'image' => 'kampas3' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Kampas Belakang Vario Beat Scoopy Spacy',
                'deskripsi_singkat' => 'Kampas Belakang',
                'deskripsi' => 'Kampas rem belakang bisa digunakan untuk motor Vario,Beat,Scoopy,Spacy,Vario 150 Esp,Beat Esp, Beat Pop Esp,Verza',
                'harga_normal' => 60000,
                'SKU' => 'ONDR0014',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'kampas4' . '.jpg',
            ],
            [
                'nama_produk' => 'Morro Kampas Rem',
                'deskripsi_singkat' => 'Kampas Rem Tromol',
                'deskripsi' => 'Kampas rem tromol digunakan untuk motor Vega ZR',
                'harga_normal' => 55000,
                'SKU' => 'ONDR0015',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'kampas5' . '.jpg',
            ],
            [
                'nama_produk' => 'Morro Kampas Rem Tromol',
                'deskripsi_singkat' => 'Kampas Rem Tromol',
                'deskripsi' => 'Kampas rem tromol digunakan untuk motor Grand',
                'harga_normal' => 55000,
                'SKU' => 'ONDR0016',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'kampas6' . '.jpg',
            ],
            [
                'nama_produk' => 'Ss Kain Rem',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem depan digunakan untuk motor jupiter Mx',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0017',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'kampas7' . '.jpg',
            ],
            [
                'nama_produk' => 'Brio Kampas Rem Depan',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem Depan digunakan untuk motor Blade',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0018',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'kampas8' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Kampas Rem Depan',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem Depan digunakan untuk motor honda',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0019',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'kampas9' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamaha Kampas Rem Depan',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem Depan digunakan untuk motor Jupiter Mx,Jupiter Mx New,Vixion,Vixion New, Xabre',
                'harga_normal' => 65000,
                'SKU' => 'ONDR0020',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'kampas10' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamaha Kampas Rem Depan NMAX',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem Depan digunakan untuk motor Nmax,Mio M3,Mx King',
                'harga_normal' => 65000,
                'SKU' => 'ONDR0021',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'kampas11' . '.jpg',
            ],
            [
                'nama_produk' => 'Modish Spion Tuton',
                'deskripsi_singkat' => 'Spion Tuton',
                'deskripsi' => 'Spion Tuton Variasi',
                'harga_normal' => 75000,
                'SKU' => 'ONDR0022',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'spion' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Kampas Depan',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem Depan digunakan untuk motor Blade,Blade New,Blade 125,Absolute Revo,Revo F1',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0023',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'kampas13' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Kampas Rem Depan Beat Beat Fi Beat Esp Beat Pop Esp',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem Depan digunakan untuk motor Beat,Beat Fi,Beat Esp,Beat Pop Esp,Vario Techno',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0024',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'kampas14' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Kampas Rem Depan Supra X 125 Supra X 125 Fi Blade New',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem Depan digunakan untuk motor Supra X 125,Supra X 125 Fi,Blade New',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0025',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'kampas15' . '.jpg',
            ],
            [
                'nama_produk' => 'Brio Kampas Rem Depan Supra X',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem depan digunakan untuk motor Supra X',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0026',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'kampas16' . '.jpg',
            ],
            [
                'nama_produk' => 'Brio kampas rem depan Satria R',
                'deskripsi_singkat' => 'kampas rem depan',
                'deskripsi' => 'kampas rem depan digunakan untuk motor Satria Rr',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0027',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'kampas17' . '.jpg',
            ],
            [
                'nama_produk' => 'Thailand Kampas Rem Depan',
                'deskripsi_singkat' => 'Kampas Rem Depan',
                'deskripsi' => 'Kampas Rem depan digunakan untuk motor Thunder 125',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0028',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'kampas18' . '.jpg',
            ],
            [
                'nama_produk' => 'Hokage Bearing As Roda',
                'deskripsi_singkat' => 'Bearing As Roda',
                'deskripsi' => 'Bearing digunakan untuk menjaga as roda agar tidak bergesekan dengan rumah (Roda)',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0029',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'klahar1' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Bearing As roda',
                'deskripsi_singkat' => 'Bearing As roda',
                'deskripsi' => 'Bearing digunakan untuk menjaga as roda agar tidak bergesekan dengan rumah (Roda)',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0030',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 58,
                'image' => 'klahar2' . '.jpg',
            ],
            [
                'nama_produk' => 'Moxis',
                'deskripsi_singkat' => 'Bearing As Roda',
                'deskripsi' => 'Bearing digunakan untuk menjaga as roda agar tidak bergesekan dengan rumah (Roda)',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0031',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'klahar3' . '.jpg',
            ],
            [
                'nama_produk' => 'Rtd Rayton',
                'deskripsi_singkat' => 'Lampu utama Led',
                'deskripsi' => 'Lampu Led ini memiliki terang  9-18v, bisa digunakan berbagai motor',
                'harga_normal' => 150000,
                'SKU' => 'ONDR0032',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'lampu1' . '.jpg',
            ],
            [
                'nama_produk' => 'Auto Lamp Bulbs',
                'deskripsi_singkat' => 'Lampu belakang (Stop rem)',
                'deskripsi' => 'lampu belakang memiliki 2 mode, menyala standby dan saat di rem menyala terang',
                'harga_normal' => 12000,
                'SKU' => 'ONDR0033',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'lampu2' . '.jpg',
            ],
            [
                'nama_produk' => 'Kiehan',
                'deskripsi_singkat' => 'Lampu belakang (Stop rem)',
                'deskripsi' => 'lampu belakang memiliki 2 mode, menyala standby dan saat di rem menyala terang',
                'harga_normal' => 10000,
                'SKU' => 'ONDR0034',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'lampu3' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamaha Lampu Bohlam Depan',
                'deskripsi_singkat' => 'Lampu bohlam depan',
                'deskripsi' => 'Lampu bohlam depan, yamaha genuine parts ',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0035',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'lampu4' . '.jpg',
            ],
            [
                'nama_produk' => 'Osram',
                'deskripsi_singkat' => 'Lampu bohlam depan',
                'deskripsi' => 'Lampu bohlam depan memiliki terang 12v',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0036',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'lampu5' . '.jpg',
            ],
            [
                'nama_produk' => 'Philips Hs1',
                'deskripsi_singkat' => 'Lampu bohlam depan',
                'deskripsi' => 'Lampu bohlam depan philips Hs1 35w 12volt',
                'harga_normal' => 32000,
                'SKU' => 'ONDR0037',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'lampu6' . '.jpg',
            ],
            [
                'nama_produk' => 'Aspira bohlam depan atau lampu depan',
                'deskripsi_singkat' => 'Lampu bohlam depan',
                'deskripsi' => 'bohlam depan atau lampu depan merk Aspira kualitas Astra asli',
                'harga_normal' => 18000,
                'SKU' => 'ONDR0038',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'lampu7' . '.jpg',
            ],
            [
                'nama_produk' => 'T10 Rgb',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu sein led T10 Rgb + remote, 12v (hanya untuk arus DC)',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0039',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'sein1' . '.jpg',
            ],
            [
                'nama_produk' => 'Bht Lampu stop rem led',
                'deskripsi_singkat' => 'Lampu stop rem led',
                'deskripsi' => 'Lampu Belakang Stop rem motor, led kedip 13 mata led 12v,warna merah',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0040',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein2' . '.jpg',
            ],
            [
                'nama_produk' => 'Czr',
                'deskripsi_singkat' => 'Lampu stop rem led',
                'deskripsi' => 'Lampu belakang motor led kedip, warna biru ',
                'harga_normal' => 22000,
                'SKU' => 'ONDR0041',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'sein3' . '.jpg',
            ],
            [
                'nama_produk' => 'Shinagawa led kedip Putih',
                'deskripsi_singkat' => 'Lampu stop rem led',
                'deskripsi' => 'Lampu belakang stop rem motor led kedip, warna putih',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0042',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein4' . '.jpg',
            ],
            [
                'nama_produk' => 'Hinowa led kedip',
                'deskripsi_singkat' => 'Lampu stop rem led',
                'deskripsi' => 'Lampu belakang stop rem motor led kedip, warna biru',
                'harga_normal' => 23000,
                'SKU' => 'ONDR0043',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein5' . '.jpg',
            ],
            [
                'nama_produk' => 'Bht Lampu Sein Led White',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu sein led 12v, warna white light',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0044',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'sein6' . '.jpg',
            ],
            [
                'nama_produk' => 'Led Lampu sein led 12v',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu sein led 12v, warna Merah',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0045',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'sein7' . '.jpg',
            ],
            [
                'nama_produk' => 'Bht Lampu Sein Led Biru',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led 12v, warna Biru',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0046',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein8' . '.jpg',
            ],
            [
                'nama_produk' => 'Proptaper',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led, warna Biru',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0047',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein9' . '.jpg',
            ],
            [
                'nama_produk' => 'Zeus Lampu Sein Led 12v Merah',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led 12v, Warna Merah',
                'harga_normal' => 12000,
                'SKU' => 'ONDR0048',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein10' . '.jpg',
            ],
            [
                'nama_produk' => 'Led Lampu Sein Led 12v Biru',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led 12v, Warna Biru',
                'harga_normal' => 12000,
                'SKU' => 'ONDR0049',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein11' . '.jpg',
            ],
            [
                'nama_produk' => 'Cr 2860',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein led 12v, Warna Hijau',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0050',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'sein12' . '.jpg',
            ],
            [
                'nama_produk' => 'Hinowa ampu Sein Led 12v',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led 12v, Warna Kuning',
                'harga_normal' => 12000,
                'SKU' => 'ONDR0051',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein13' . '.jpg',
            ],
            [
                'nama_produk' => 'Led Lampu Sein Led 12v Merah',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led 12v, warna Merah',
                'harga_normal' => 12000,
                'SKU' => 'ONDR0052',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein14' . '.jpg',
            ],
            [
                'nama_produk' => 'Zeus Lampu Sein Led 12v',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led 12v, warna merah',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0053',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein15' . '.jpg',
            ],
            [
                'nama_produk' => 'Protaper',
                'deskripsi_singkat' => 'Lampu Sein Led',
                'deskripsi' => 'Lampu Sein Led kedip 12v, warna putih',
                'harga_normal' => 12000,
                'SKU' => 'ONDR0054',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sein16' . '.jpg',
            ],
            [
                'nama_produk' => 'Ahm Oil',
                'deskripsi_singkat' => 'Oli gearbox matic',
                'deskripsi' => 'Oli gearbox ahm honda, 10w-30 Api Sl, Berat 120ml',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0055',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'gardan1' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamalube Oli gearbox yamalube 10w-40',
                'deskripsi_singkat' => 'Oli gearbox matic',
                'deskripsi' => 'Oli gearbox yamalube 10w-40, berat 140ml ',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0056',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'gardan2' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamalube Oli gearbox Matic',
                'deskripsi_singkat' => 'Oli gearbox matic',
                'deskripsi' => 'Oli gearbox yamalube, berat 100ml',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0057',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'gardan3' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamaha Vanbelt',
                'deskripsi_singkat' => 'vanbelt',
                'deskripsi' => 'vanbelt yamaha 2ph-e7641-88',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0058',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'panbel1' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Vanbelt Fullset',
                'deskripsi_singkat' => 'vanbelt',
                'deskripsi' => 'vanbelt 1 set',
                'harga_normal' => 75000,
                'SKU' => 'ONDR0059',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'panbel2' . '.jpg',
            ],
            [
                'nama_produk' => 'Thailand Vanbelt Yamaha 2ph',
                'deskripsi_singkat' => 'vanbelt',
                'deskripsi' => 'vanbelt yamaha 2ph-17641-00',
                'harga_normal' => 100000,
                'SKU' => 'ONDR0060',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'panbel3' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk vanbelt',
                'deskripsi_singkat' => 'vanbelt',
                'deskripsi' => 'vanbelt',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0061',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'panbel4' . '.jpg',
            ],
            [
                'nama_produk' => 'Kit Motor',
                'deskripsi_singkat' => 'Kit Motor Multiguna',
                'deskripsi' => 'Mengkilapkan & Melindungi seluruh bodi motor',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0062',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'semir1' . '.jpg',
            ],
            [
                'nama_produk' => 'Kit Black',
                'deskripsi_singkat' => 'Kit Black Magic',
                'deskripsi' => 'Mengkilapkan ban kendaraan menjadi hitam seperti baru',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0063',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'semir2' . '.jpg',
            ],
            [
                'nama_produk' => 'Bad Jalu As Roda',
                'deskripsi_singkat' => 'Jalu As Roda',
                'deskripsi' => 'Jalu As Roda menambah tampilan kendaraan menjadi lebih kece',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0064',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'jalu2' . '.jpg',
            ],
            [
                'nama_produk' => 'Fast Bikes',
                'deskripsi_singkat' => 'Jalu As Roda',
                'deskripsi' => 'Jalu As Roda menambah tampilan kendaraan menjadi lebih kece',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0065',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'jalu' . '.jpg',
            ],
            [
                'nama_produk' => 'Baut L ',
                'deskripsi_singkat' => 'Baut L Monel',
                'deskripsi' => 'Baut L Monel body motor',
                'harga_normal' => 3000,
                'SKU' => 'ONDR0066',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'baut' . '.jpg',
            ],
            [
                'nama_produk' => 'Carb Cleaner',
                'deskripsi_singkat' => 'Carbo Cleaner',
                'deskripsi' => 'Carbo Cleaner pelumas rantai kendaraan, membersihkan kerak pada mesin',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0067',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'carbucleaner' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Karet Seal Shok',
                'deskripsi_singkat' => 'Karet Seal Shok',
                'deskripsi' => 'Karet Seal Shok model Grand',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0068',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'karetseal' . '.jpg',
            ],
            [
                'nama_produk' => 'New Crom',
                'deskripsi_singkat' => 'Packing Knalpot',
                'deskripsi' => 'Packing Knalpot/Perpak model vario',
                'harga_normal' => 5000,
                'SKU' => 'ONDR0069',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'perpak' . '.jpg',
            ],
            [
                'nama_produk' => 'Aspira',
                'deskripsi_singkat' => 'Lem Gasket',
                'deskripsi' => 'Lem Gasket atau Lem Paking',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0070',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'lemgasket' . '.jpg',
            ],
            [
                'nama_produk' => 'Auto Sealer',
                'deskripsi_singkat' => 'Lem Sealer silicone',
                'deskripsi' => 'Lem Sealer silicone digunakan menutup bagian paking',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0071',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'lemsealer' . '.jpg',
            ],
            [
                'nama_produk' => 'Express Ban Dalam 14',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 2.50/2.75 - 14',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0072',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'dalam1' . '.jpg',
            ],
            [
                'nama_produk' => 'ExpressBan Dalam 17',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 2.25/2.50 - 17',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0073',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'dalam2' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam 80-90',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 80/90 - 14, 90/80 - 14,90/90 - 14, 2.75/3.00 - 14',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0074',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'dalam4' . '.jpg',
            ],
            [
                'nama_produk' => 'Ban Dalam Rca Inner Tub',
                'deskripsi_singkat' => 'Ban Dalam Rca Inner Tube',
                'deskripsi' => 'Ban Dalam ukuran  2.50/2.75 - 17',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0075',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'dalam3' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam 70-90',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 70/90 - 14, 80/80 - 14',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0076',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'dalam5' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam 225-250',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 2.25/2.50 - 17, 70/90 - 17',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0077',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'dalam6' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam ukuran 2.50',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 2.50/2.75 - 17, 70/90 - 17, 80/90 - 17',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0078',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'dalam7' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam ukuran 3.00',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 3.00/3.25 - 17, 90/90 - 17, 80/100 - 17, 100/70 - 17',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0079',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'dalam8' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam ukuran 70-90',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 70/90 - 16',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0080',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'dalam9' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam ukuran 80-90',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 80/90 - 16',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0081',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'dalam10' . '.jpg',
            ],
            [
                'nama_produk' => 'Aspira Ban Dalam ukuran 70-90',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 70/90 - 17',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0082',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'dalam11' . '.jpg',
            ],
            [
                'nama_produk' => 'Mizzle Ban Dalam ukuran 50-90',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam Ukuran 50/90 - 17',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0083',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'dalam12' . '.jpg',
            ],
            [
                'nama_produk' => 'Mizzle Ban Dalam ukuran 60-90',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 60/90 - 14, 60/100 - 14',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0084',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'dalam13' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Dalam ukuran 3.50',
                'deskripsi_singkat' => 'Ban Dalam',
                'deskripsi' => 'Ban Dalam ukuran 3.50/4.00 - 10',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0085',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'dalam14' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Ban Luar ukuran 110-80',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Ban Luar ukuran 110/80 - 17',
                'harga_normal' => 270000,
                'SKU' => 'ONDR0086',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar1' . '.jpg',
            ],
            [
                'nama_produk' => 'Honda Ban Luar ukuran 90-90',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Ban Luar ukuran 90/90 - 14',
                'harga_normal' => 225000,
                'SKU' => 'ONDR0087',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar2' . '.jpg',
            ],
            [
                'nama_produk' => 'Kingland Ban Luar ukuran 80',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Ban Luar ukuran 80/90 - 14',
                'harga_normal' => 240000,
                'SKU' => 'ONDR0088',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar3' . '.jpg',
            ],
            [
                'nama_produk' => 'Kingland Ban Luar 90',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Ban Luar ukuran 90/90 - 14',
                'harga_normal' => 255000,
                'SKU' => 'ONDR0089',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar4' . '.jpg',
            ],
            [
                'nama_produk' => 'Fdr Tire Ban Luar Fdr Flemino',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Tipe Fdr Flemino ukuran 80/90 - 14',
                'harga_normal' => 195000,
                'SKU' => 'ONDR0090',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar5' . '.jpg',
            ],
            [
                'nama_produk' => 'Fdr Tire Ban Luar Fdr Spartax',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Tipe Fdr Spartax ukuran 80/90 - 14',
                'harga_normal' => 220000,
                'SKU' => 'ONDR0091',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar6' . '.jpg',
            ],
            [
                'nama_produk' => 'Fdr TireBan Luar Fdr Genzi Pro',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Tipe Fdr Genzi Pro ukuran 90/80 - 14',
                'harga_normal' => 235000,
                'SKU' => 'ONDR0092',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar7' . '.jpg',
            ],
            [
                'nama_produk' => 'Fdr Tire Ban Luar Fdr Facio',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Tipe Fdr Facio ukuran 90/90 - 14',
                'harga_normal' => 215000,
                'SKU' => 'ONDR0093',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar8' . '.jpg',
            ],
            [
                'nama_produk' => 'Irc Tire Ban Luar',
                'deskripsi_singkat' => 'Ban Luar',
                'deskripsi' => 'Tipe Irc Reborn ukuran 100/80 - 14',
                'harga_normal' => 255000,
                'SKU' => 'ONDR0094',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'luar9' . '.jpg',
            ],
            [
                'nama_produk' => 'Modish Breket Knalpot',
                'deskripsi_singkat' => 'Breket Knalpot',
                'deskripsi' => 'Breket Knalpot atau penyangga knalpot',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0095',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'breket1' . '.jpg',
            ],
            [
                'nama_produk' => 'Sharky',
                'deskripsi_singkat' => 'Breket Knalpot',
                'deskripsi' => 'Breket knalpot atau kleman knalpot',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0096',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'breket2' . '.jpg',
            ],
            [
                'nama_produk' => 'Igawa',
                'deskripsi_singkat' => 'Gantungan barang',
                'deskripsi' => 'Gantungan Barang warna',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0097',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'gantungan1' . '.jpg',
            ],
            [
                'nama_produk' => 'Msx',
                'deskripsi_singkat' => 'Gantungan barang',
                'deskripsi' => 'Gantungan Barang Warna',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0098',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'gantungan2' . '.jpg',
            ],
            [
                'nama_produk' => 'Domino',
                'deskripsi_singkat' => 'Handgrip',
                'deskripsi' => 'Handgrip memberikan kenyamanan dalam memegang stang',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0099',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'grip1' . '.jpg',
            ],
            [
                'nama_produk' => 'Cha',
                'deskripsi_singkat' => 'Handgrip',
                'deskripsi' => 'Handgrip memberikan kenyamanan dalam memegang stang',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0101',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'grip2' . '.jpg',
            ],
            [
                'nama_produk' => 'Bad Handle Rem',
                'deskripsi_singkat' => 'Handle Rem',
                'deskripsi' => 'Handle Rem untuk motor Vario',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0102',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'handle1' . '.jpg',
            ],
            [
                'nama_produk' => 'Vni Handle Rem',
                'deskripsi_singkat' => 'Handle Rem',
                'deskripsi' => 'Handle Rem warna',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0103',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'handle2' . '.jpg',
            ],
            [
                'nama_produk' => 'Hokage Comstir untuk motor supra',
                'deskripsi_singkat' => 'Comstir',
                'deskripsi' => 'Comstir untuk motor supra',
                'harga_normal' => 80000,
                'SKU' => 'ONDR0104',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'kom1' . '.jpg',
            ],
            [
                'nama_produk' => 'Mb Comstir',
                'deskripsi_singkat' => 'Comstir',
                'deskripsi' => 'Comstir untuk motor grand',
                'harga_normal' => 80000,
                'SKU' => 'ONDR0105',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'kom2' . '.jpg',
            ],
            [
                'nama_produk' => 'Termignoni',
                'deskripsi_singkat' => 'Lampu utama Led',
                'deskripsi' => 'Lampu Utama Led',
                'harga_normal' => 65000,
                'SKU' => 'ONDR0106',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'lampu1' . '.jpg',
            ],
            [
                'nama_produk' => 'Ayoto Lampu Utama Led',
                'deskripsi_singkat' => 'Lampu Utama Led',
                'deskripsi' => 'Lampu Utama Led',
                'harga_normal' => 70000,
                'SKU' => 'ONDR0107',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 50,
                'image' => 'lampu2' . '.jpg',
            ],
            [
                'nama_produk' => 'Thailand Master Rem Kit',
                'deskripsi_singkat' => 'Master Rem Kit',
                'deskripsi' => 'Master Rem Kit untuk motor Satria 150',
                'harga_normal' => 60000,
                'SKU' => 'ONDR0108',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'master1' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Master Rem Kit',
                'deskripsi_singkat' => 'Master Rem Kit',
                'deskripsi' => 'Master Rem Kit untuk motor Jupiter Z',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0109',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'master2' . '.jpg',
            ],
            [
                'nama_produk' => 'Oribaru Master Rem Kit',
                'deskripsi_singkat' => 'Master Rem Kit',
                'deskripsi' => 'Master Rem Kit untuk motor Mio',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0110',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'master3' . '.jpg',
            ],
            [
                'nama_produk' => 'Primaxp Oli Mesin',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin ukuran 1 Liter',
                'harga_normal' => 55000,
                'SKU' => 'ONDR0111',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli1' . '.jpg',
            ],
            [
                'nama_produk' => 'Mesran Oli Mesin',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin Ukuran 1 Liter',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0112',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli2' . '.jpg',
            ],
            [
                'nama_produk' => 'Enduro Oli Mesin Matic',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin untuk Matic ukuran 0.8 Liter',
                'harga_normal' => 52000,
                'SKU' => 'ONDR0113',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli3' . '.jpg',
            ],
            [
                'nama_produk' => 'Enduro Oli Mesin',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin untuk Matic ukuran 0.8 Liter',
                'harga_normal' => 54000,
                'SKU' => 'ONDR0114',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli4' . '.jpg',
            ],
            [
                'nama_produk' => 'Enduro 4T',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin ukuran 0.8 Liter',
                'harga_normal' => 47000,
                'SKU' => 'ONDR0115',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli5' . '.jpg',
            ],
            [
                'nama_produk' => 'Castrol Matic',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin untuk Matic ukuran 800ml',
                'harga_normal' => 48000,
                'SKU' => 'ONDR0116',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli6' . '.jpg',
            ],
            [
                'nama_produk' => 'Castrol Activ',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin ukuran 800ml',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0117',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli7' . '.jpg',
            ],
            [
                'nama_produk' => 'Enduro 4T Racing',
                'deskripsi_singkat' => 'Oli Mesin ',
                'deskripsi' => 'Oli Mesin ukuran 1 Liter',
                'harga_normal' => 52000,
                'SKU' => 'ONDR0118',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli8' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamalube Oli Mesin super matic',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin super matic ukuran 1 Liter',
                'harga_normal' => 74000,
                'SKU' => 'ONDR0119',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli9' . '.jpg',
            ],
            [
                'nama_produk' => 'Castrol 2T',
                'deskripsi_singkat' => 'Oli Samping',
                'deskripsi' => 'Oli Samping motor 2 tak ukuran 700ml',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0120',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli10' . '.jpg',
            ],
            [
                'nama_produk' => 'Castrol Go',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin motor bebek ukuran 800ml',
                'harga_normal' => 38000,
                'SKU' => 'ONDR0121',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli11' . '.jpg',
            ],
            [
                'nama_produk' => 'Evalube Pro',
                'deskripsi_singkat' => 'Oli Samping',
                'deskripsi' => 'Oli Samping motor 2 tak ukuran 0.7 Liter',
                'harga_normal' => 31000,
                'SKU' => 'ONDR0122',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli12' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamalube Oli Mesin motor bebek',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin motor bebek ukuran 1 liter ',
                'harga_normal' => 57000,
                'SKU' => 'ONDR0123',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli13' . '.jpg',
            ],
            [
                'nama_produk' => 'Ecstar',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'cocok digunakan untuk semua motor bebek suzuki, ukuran 0.8 L',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0124',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli14' . '.jpg',
            ],
            [
                'nama_produk' => 'Yamalube Gold',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin digunakan untuk semua motor bebek yamaha, ukuran 0.8 L',
                'harga_normal' => 53000,
                'SKU' => 'ONDR0125',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli15' . '.jpg',
            ],
            [
                'nama_produk' => 'Federal',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli Mesin digunakan untuk matic, ukuran 800 ml',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0126',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli16' . '.jpg',
            ],
            [
                'nama_produk' => 'Federal ultratec',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Cocok digunakan untuk motor bebek dengan beban kerja berat, ukuran 800ml',
                'harga_normal' => 37000,
                'SKU' => 'ONDR0127',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli17' . '.jpg',
            ],
            [
                'nama_produk' => 'Mpx1',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Mpx1 cocok untuk motor dengan tipe kopling basah dengan transmisi manual seperti motor bebek dan sport, ukuran 0.8L',
                'harga_normal' => 33000,
                'SKU' => 'ONDR0128',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli18' . '.jpg',
            ],
            [
                'nama_produk' => 'Mpx2',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Mpx2 cocok untuk motor matic, ukuran 0.8L',
                'harga_normal' => 38000,
                'SKU' => 'ONDR0129',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli19' . '.jpg',
            ],
            [
                'nama_produk' => 'Shell Oli mesin khusus untuk motor matic',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli mesin khusus untuk motor matic, ukuran 0.8L',
                'harga_normal' => 47000,
                'SKU' => 'ONDR0130',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli20' . '.jpg',
            ],
            [
                'nama_produk' => 'Shell Oli mesin khusus motor bebek',
                'deskripsi_singkat' => 'Oli Mesin',
                'deskripsi' => 'Oli mesin khusus motor bebek maupun matic, ukuran 0.8L',
                'harga_normal' => 48000,
                'SKU' => 'ONDR0131',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli21' . '.jpg',
            ],
            [
                'nama_produk' => 'Shell Sx',
                'deskripsi_singkat' => 'Oli Samping',
                'deskripsi' => 'Oli Samping motor 2 tak, ukuran 0.7L',
                'harga_normal' => 36000,
                'SKU' => 'ONDR0132',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli22' . '.jpg',
            ],
            [
                'nama_produk' => 'Idemitsu',
                'deskripsi_singkat' => 'Oli Samping',
                'deskripsi' => 'Oli Samping motor 2 tak, ukuran 0.8L',
                'harga_normal' => 57000,
                'SKU' => 'ONDR0133',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'oli23' . '.jpg',
            ],
            [
                'nama_produk' => 'Thaita Proguard Motor',
                'deskripsi_singkat' => 'Proguard Motor',
                'deskripsi' => 'berguna mencegah tuas rem tertekan saat motor bersenggolan atau terjatuh',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0134',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'guard1' . '.jpg',
            ],
            [
                'nama_produk' => 'Cr7 Proguard Motor',
                'deskripsi_singkat' => 'Proguard Motor',
                'deskripsi' => 'berguna mencegah tuas rem tertekan saat motor bersenggolan atau terjatuh',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0135',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 55,
                'image' => 'guard2' . '.jpg',
            ],
            [
                'nama_produk' => 'Racenui Raiser Peninggi Stang',
                'deskripsi_singkat' => 'Raiser Peninggi Stang',
                'deskripsi' => 'Peninggi stang bisa digunakan untuk motor kopling',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0136',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'peninggi1' . '.jpg',
            ],
            [
                'nama_produk' => 'Minion Raiser Peninggi Stang',
                'deskripsi_singkat' => 'Raiser Peninggi Stang',
                'deskripsi' => 'Peninggi stang bisa digunakan untuk motor kopling',
                'harga_normal' => 55000,
                'SKU' => 'ONDR0137',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'peninggi2' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Roller Racing Vario 150',
                'deskripsi_singkat' => 'Roller Racing',
                'deskripsi' => 'digunakan untuk motor vario 150, ukuran 9gram',
                'harga_normal' => 60000,
                'SKU' => 'ONDR0138',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'roller1' . '.jpg',
            ],
            [
                'nama_produk' => 'Trq Roller',
                'deskripsi_singkat' => 'Roller',
                'deskripsi' => 'digunakan untuk motor beat pop, ukuran 8gram',
                'harga_normal' => 35000,
                'SKU' => 'ONDR0139',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'roller2' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Roller Racing Mio J',
                'deskripsi_singkat' => 'Roller Racing',
                'deskripsi' => 'digunakan untuk motor mio j, ukuran 9gram',
                'harga_normal' => 60000,
                'SKU' => 'ONDR0140',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'roller3' . '.jpg',
            ],
            [
                'nama_produk' => 'Thailand Roller',
                'deskripsi_singkat' => 'Roller',
                'deskripsi' => 'digunakan untuk motor mio, ukuran 9gram',
                'harga_normal' => 50000,
                'SKU' => 'ONDR0141',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'roller4' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Roller Racing',
                'deskripsi_singkat' => 'Roller Racing',
                'deskripsi' => 'digunakan untuk motor mio m3, ukuran 9gram',
                'harga_normal' => 60000,
                'SKU' => 'ONDR0142',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'roller5' . '.jpg',
            ],
            [
                'nama_produk' => 'Hiqdal Sein Kuping',
                'deskripsi_singkat' => 'Sein Kuping',
                'deskripsi' => 'sein kuping lampu sen 12volt',
                'harga_normal' => 65000,
                'SKU' => 'ONDR0143',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'sen1' . '.jpg',
            ],
            [
                'nama_produk' => 'Cr7 Sein Kuping',
                'deskripsi_singkat' => 'Sein Kuping',
                'deskripsi' => 'untuk motor vixion new',
                'harga_normal' => 75000,
                'SKU' => 'ONDR0144',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'sen2' . '.jpg',
            ],
            [
                'nama_produk' => 'Rpm Step Depan Karet',
                'deskripsi_singkat' => 'Step Depan',
                'deskripsi' => 'Step depan bahan karet di berkati dengan cover stainless',
                'harga_normal' => 45000,
                'SKU' => 'ONDR0145',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'step1' . '.jpg',
            ],
            [
                'nama_produk' => 'Md-1 Step Belakang',
                'deskripsi_singkat' => 'Step Belakang',
                'deskripsi' => 'Step belakang terbuat dari bahan stainless',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0146',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 53,
                'image' => 'step2' . '.jpg',
            ],
            [
                'nama_produk' => 'Rpm Step Depan',
                'deskripsi_singkat' => 'Step Depan',
                'deskripsi' => 'Step depan terbuat dari bahan karet',
                'harga_normal' => 40000,
                'SKU' => 'ONDR0147',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'step3' . '.jpg',
            ],
            [
                'nama_produk' => 'Alfacini Step Depan',
                'deskripsi_singkat' => 'Step Depan',
                'deskripsi' => 'Step depan terbuat dari bahan karet',
                'harga_normal' => 30000,
                'SKU' => 'ONDR0148',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'step4' . '.jpg',
            ],
            [
                'nama_produk' => 'Kitaco Saklar stater',
                'deskripsi_singkat' => 'Saklar stater',
                'deskripsi' => 'Saklar Stater ',
                'harga_normal' => 70000,
                'SKU' => 'ONDR0149',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'saklar1' . '.jpg',
            ],
            [
                'nama_produk' => 'Edo Kunci Kontak',
                'deskripsi_singkat' => 'Kunci Kontak',
                'deskripsi' => 'Kunci Kontak 1 set dengan kunci jok',
                'harga_normal' => 160000,
                'SKU' => 'ONDR0150',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'kontak1' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Saklar',
                'deskripsi_singkat' => 'Saklar',
                'deskripsi' => 'Saklar lampu',
                'harga_normal' => 85000,
                'SKU' => 'ONDR0151',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'saklar2' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Kunci kontak',
                'deskripsi_singkat' => 'Kunci kontak',
                'deskripsi' => 'Kunci Kontak 1 set dengan kunci jok',
                'harga_normal' => 185000,
                'SKU' => 'ONDR0152',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'kontak2' . '.jpg',
            ],
            [
                'nama_produk' => 'Shinagawa Saklar Lampu',
                'deskripsi_singkat' => 'Saklar Lampu',
                'deskripsi' => 'Saklar lampu 1 mode on/of',
                'harga_normal' => 25000,
                'SKU' => 'ONDR0153',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'saklar3' . '.jpg',
            ],
            [
                'nama_produk' => 'Fastbikes Tabung Minyak Rem',
                'deskripsi_singkat' => 'Tabung Minyak Rem',
                'deskripsi' => 'Tabung Minyak Rem variasi',
                'harga_normal' => 60000,
                'SKU' => 'ONDR0154',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'tabung1' . '.jpg',
            ],
            [
                'nama_produk' => 'Brembo Tabung Minyak Rem',
                'deskripsi_singkat' => 'Tabung Minyak Rem',
                'deskripsi' => 'Tabung Minyak Rem variasi',
                'harga_normal' => 70000,
                'SKU' => 'ONDR0155',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'tabung2' . '.jpg',
            ],
            [
                'nama_produk' => 'Nisin Tabung Minyak Rem',
                'deskripsi_singkat' => 'Tabung Minyak Rem',
                'deskripsi' => 'Tabung Minyak Rem variasi',
                'harga_normal' => 75000,
                'SKU' => 'ONDR0156',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'tabung3' . '.jpg',
            ],
            [
                'nama_produk' => 'Morin Selang Oli Gardan',
                'deskripsi_singkat' => 'Selang Oli Gardan',
                'deskripsi' => 'Selang Oli Gardan variasi',
                'harga_normal' => 90000,
                'SKU' => 'ONDR0157',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'selang1' . '.jpg',
            ],
            [
                'nama_produk' => 'Cks Tutup Oli Selang',
                'deskripsi_singkat' => 'Tutup Oli Selang',
                'deskripsi' => 'Tutup Oli Selang variasi',
                'harga_normal' => 75000,
                'SKU' => 'ONDR0158',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'selang2' . '.jpg',
            ],
            [
                'nama_produk' => 'Morin Selang Oli Gardan',
                'deskripsi_singkat' => 'Selang Oli Gardan',
                'deskripsi' => 'Selang Oli Gardan variasi',
                'harga_normal' => 80000,
                'SKU' => 'ONDR0159',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'selang3' . '.jpg',
            ],
            [
                'nama_produk' => 'Breket Minum',
                'deskripsi_singkat' => 'Breket Minum',
                'deskripsi' => 'Breket minum botol',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0160',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 54,
                'image' => 'breketminum' . '.jpg',
            ],
            [
                'nama_produk' => 'Ipk Piting Lampu',
                'deskripsi_singkat' => 'Piting Lampu',
                'deskripsi' => 'Piting Lampu depan motor',
                'harga_normal' => 15000,
                'SKU' => 'ONDR0161',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 52,
                'image' => 'pitinglampu' . '.jpg',
            ],
            [
                'nama_produk' => 'Panom Sarung Handle',
                'deskripsi_singkat' => 'Sarung Handle',
                'deskripsi' => 'Sarung handle rem',
                'harga_normal' => 20000,
                'SKU' => 'ONDR0162',
                'status_stok' => 'Tersedia',
                'jumlah_stok' => 51,
                'image' => 'sarunghandle' . '.jpg',
            ],
        ];

        $categories = Category::pluck('id')->toArray();

        if ($this->index >= count($productData)) {
            $this->index = 0; // Reset index kembali ke 0
        }

        $namaProduk = $productData[$this->index]['nama_produk'];
        $slug = Str::slug($namaProduk);

        // Cek apakah slug sudah ada, jika ya, tambahkan sufiks numerik
        $counter = 2;
        while (Product::where('slug', $slug)->exists()) {
            $slug = $namaProduk . '-' . $counter;
            $counter++;
        }

        return $productData[$this->index++] + [
            'slug' => $slug,
            'category_id' => $this->faker->randomElement($categories)
        ];
    }
}
